// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=js+dts"
// @generated from file auth/v1/auth.proto (package auth.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { LoginRequest, LoginResponse, MeRequest, MeResponse, SignUpRequest, SignUpResponse } from "./auth_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service auth.v1.AuthService
 */
export declare const AuthService: {
  readonly typeName: "auth.v1.AuthService",
  readonly methods: {
    /**
     * @generated from rpc auth.v1.AuthService.SignUp
     */
    readonly signUp: {
      readonly name: "SignUp",
      readonly I: typeof SignUpRequest,
      readonly O: typeof SignUpResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.v1.AuthService.Login
     */
    readonly login: {
      readonly name: "Login",
      readonly I: typeof LoginRequest,
      readonly O: typeof LoginResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.v1.AuthService.Me
     */
    readonly me: {
      readonly name: "Me",
      readonly I: typeof MeRequest,
      readonly O: typeof MeResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

