// @generated by protoc-gen-es v1.4.1 with parameter "target=js+dts"
// @generated from file auth/v1/auth.proto (package auth.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message auth.v1.UserInfo
 */
export const UserInfo = proto3.makeMessageType(
  "auth.v1.UserInfo",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message auth.v1.SignUpRequest
 */
export const SignUpRequest = proto3.makeMessageType(
  "auth.v1.SignUpRequest",
  () => [
    { no: 1, name: "user_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message auth.v1.SignUpResponse
 */
export const SignUpResponse = proto3.makeMessageType(
  "auth.v1.SignUpResponse",
  () => [
    { no: 1, name: "info", kind: "message", T: UserInfo },
  ],
);

/**
 * @generated from message auth.v1.LoginRequest
 */
export const LoginRequest = proto3.makeMessageType(
  "auth.v1.LoginRequest",
  () => [
    { no: 1, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message auth.v1.LoginResponse
 */
export const LoginResponse = proto3.makeMessageType(
  "auth.v1.LoginResponse",
  () => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message auth.v1.MeRequest
 */
export const MeRequest = proto3.makeMessageType(
  "auth.v1.MeRequest",
  [],
);

/**
 * @generated from message auth.v1.MeResponse
 */
export const MeResponse = proto3.makeMessageType(
  "auth.v1.MeResponse",
  () => [
    { no: 1, name: "info", kind: "message", T: UserInfo },
  ],
);

